# Importing Data-set for the Model, extract the required data and store them into variable

In [ ]:
# import load_iris function from dataset module
from sklearn.datasets import load_iris

In [ ]:
# store the imported data (bunch), an object into a variable
iris = load_iris()

In [ ]:
# prints the dataset
print (iris)

In [ ]:
# X holds the features of data set
X = iris.data

In [ ]:
# y is a vector that holds the target, it represents the class
# to which the data point belongs, since scikit expects only numbers
y = iris.target

In [ ]:
#.shape gives its dimension
print (y.shape)
print(X.shape)

# Import Knn model (Estimator,called in Scikit) from Scikit learn and initialize it (Instantiate)

In [43]:
#imports the estimator(model) from the module named neighbors
from sklearn.neighbors import KNeighborsClassifier

In [51]:
#instantite the Estimator imported above, n_neighbors is 1 nearest neighbor
knn = KNeighborsClassifier(n_neighbors=1)

In [52]:
#shows default and set parameters for knn object.if not set default values are used
print (knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


# Fit the model (pass in data for learning)

In [54]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

# Predict the output for a new random data point

In [70]:
#requires numpy2D array so list of list is passed
knn.predict([[2,3,4,2]])

array([2])

In [74]:
#pasing 2 new data point
knn.predict([[5,3,2,2],[2,4,2,1]])

array([1, 0])

# Using different value for K

In [80]:
#instantiate the model with new K
knn = KNeighborsClassifier(n_neighbors=5)
#fit the model
knn.fit(X,y)
#predict a response
knn.predict([[2,3,4,2]])


array([1])